# Generated by Django 3.2.4 on 2021-06-27 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toDoTasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='listAdd',
            field=models.CharField(blank=True, default=None, max_length=100),
        ),
    ]
