# Generated by Django 3.2.4 on 2021-06-29 02:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('formLists', '0001_initial'),
        ('toDoTasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='listAdd',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='formLists.list', verbose_name='Lists'),
        ),
    ]
