# Generated by Django 3.2.4 on 2021-06-16 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_pic_choice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='pic_choice',
            field=models.IntegerField(default=1, verbose_name='pic_choice'),
        ),
    ]
